---
- hosts: all
  become: yes

  vars:
    source_dir: '/opt/wiki-graphs'

  tasks:
    - name: Install Git
      package:
        name: git-all
        state: present

    - name: Clone the GitHub repository
      git:
        repo: 'https://github.com/allisonking/wiki-graphs.git'
        dest: '{{ source_dir }}'

    - name: Add public GPG key for MongoDB (required for ubuntu packaging)
      apt_key:
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
        keyserver: hkp://keyserver.ubuntu.com:80

    - name: Add the MongoDB repo
      apt_repository:
        repo: 'deb https://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.6 multiverse'
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb-org
        update_cache: yes

    - name: Start MongoDB
      service:
        name: mongod
        state: started

    - name: Install python3 virtual environment package
      package:
        name: python3.4-venv
        state: present

    - name: Install pip requirements
      pip:
        requirements: '{{ source_dir }}/requirements.txt'
        virtualenv: '{{ source_dir }}/venv'
        virtualenv_command: /usr/bin/python3 -m venv

    - name: Seed the database
      command: chdir='{{ source_dir }}' venv/bin/python3 app/db/seeds.py

    - name: Start flask app with gunicorn
      gunicorn:
        app: wikigraph
        chdir: '{{ source_dir }}'
        venv: '{{ source_dir }}/venv'
        conf: '/vagrant_data/gunicorn.cfg'
      environment:
        NYT_API_KEY: '{{ NYT_API_KEY }}'
